/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package home.managerinzeratov;

import entity.MestaListModel;
import java.awt.Graphics;
import java.awt.Image;
import java.beans.PropertyChangeListener;
import java.beans.PropertyChangeSupport;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author Janco1
 */
public class PridatVybraneForm extends javax.swing.JDialog {

    private List<String> vsetkyMesta = new ArrayList<String>();
    private List<String> vybraneMesta = new ArrayList<String>();
    private PropertyChangeSupport changes = new PropertyChangeSupport(this);
    private Database database;
    private Image img;

    /**
     * Creates new form PridatVybraneForm
     */
    public PridatVybraneForm(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            img = ImageIO.read(new File("backg.jpg"));
        } catch (IOException ex) {
            Logger.getLogger(MainForm2.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        setLocationRelativeTo(null);
    }

    public PridatVybraneForm(java.awt.Frame parent, boolean modal, List<String> vsetky, List<String> vybrane, Database database) {
        this(parent, modal);
        // prve nie je mesto lebo je to vsetky mesta
        for (int i = 1; i < vsetky.size(); i++) {
            String akt = vsetky.get(i).split("\\(")[0].trim();
            vsetkyMesta.add(akt);
        }
        
        // prve a posledne nie su mesto
        for (int i = 1; i < vybrane.size() - 1; i++) {
            String akt = vybrane.get(i).split("\\(")[0].trim();
            vybraneMesta.add(akt);
        }
        vybraneMestaList.setModel(new MestaListModel(vybraneMesta));
        // odstranime zo 'vsetkych' nase vybrane mesta
        for (String m:vybraneMesta){
            vsetkyMesta.remove(m);
        }
        vsetkyMestaList.setModel(new MestaListModel(vsetkyMesta));
        vybraneMestaList.setSelectedIndex(0);
        this.database=database;
    }

    public void addPropertyChangeListener(PropertyChangeListener listener) {
        changes.addPropertyChangeListener(listener);
    }

    public void removePropertyChangeListener(PropertyChangeListener listener) {
        changes.removePropertyChangeListener(listener);
    }
    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT
     * modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel(){
            protected void paintComponent(Graphics g)
            {
                g.drawImage(img, 0, 0, null);
                super.paintComponent(g);
            }
        };
        ulozitButton = new javax.swing.JButton();
        zavrietButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        vybraneMestaList = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        pridatVybraneButton = new javax.swing.JButton();
        odobratVybraneButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        vsetkyMestaList = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Pridať mesto do zoznamu vybraných");
        setResizable(false);

        jPanel1.setOpaque(false);

        ulozitButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        ulozitButton.setText("Uložiť");
        ulozitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulozitButtonActionPerformed(evt);
            }
        });

        zavrietButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        zavrietButton.setText("Zavrieť");
        zavrietButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zavrietButtonActionPerformed(evt);
            }
        });

        vybraneMestaList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(vybraneMestaList);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Vybrané mestá:");

        pridatVybraneButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pridatVybraneButton.setText(">>");
        pridatVybraneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatVybraneButtonActionPerformed(evt);
            }
        });

        odobratVybraneButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        odobratVybraneButton.setText("<<");
        odobratVybraneButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odobratVybraneButtonActionPerformed(evt);
            }
        });

        vsetkyMestaList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(vsetkyMestaList);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Všetky mestá:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(ulozitButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(zavrietButton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(pridatVybraneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(odobratVybraneButton, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(41, 41, 41))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(pridatVybraneButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(odobratVybraneButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ulozitButton)
                    .addComponent(zavrietButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zavrietButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zavrietButtonActionPerformed
        dispose();
    }//GEN-LAST:event_zavrietButtonActionPerformed

    private void odobratVybraneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odobratVybraneButtonActionPerformed
        if (vybraneMestaList.getSelectedIndex() != -1) {
            String vybrane = (String) vybraneMestaList.getSelectedValue();
            vybraneMesta.remove(vybraneMestaList.getSelectedIndex());
            vybraneMestaList.setModel(new MestaListModel(vybraneMesta));
            if (vybraneMesta.size() > 0) {
                vybraneMestaList.setSelectedIndex(0);
            }

            vsetkyMesta.add(vybrane);
            Collections.sort(vsetkyMesta);
            vsetkyMestaList.setModel(new MestaListModel(vsetkyMesta));
            vsetkyMestaList.setSelectedIndex(0);
        }
    }//GEN-LAST:event_odobratVybraneButtonActionPerformed

    private void pridatVybraneButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatVybraneButtonActionPerformed
        if (vsetkyMestaList.getSelectedIndex() != -1) {
            String vybrane = (String) vsetkyMestaList.getSelectedValue();
            vsetkyMesta.remove(vsetkyMestaList.getSelectedIndex());
            vsetkyMestaList.setModel(new MestaListModel(vsetkyMesta));
            if (vsetkyMesta.size() > 0) {
                vsetkyMestaList.setSelectedIndex(0);
            }

            vybraneMesta.add(vybrane);
            Collections.sort(vybraneMesta);
            vybraneMestaList.setModel(new MestaListModel(vybraneMesta));
            vybraneMestaList.setSelectedIndex(0);
        }
    }//GEN-LAST:event_pridatVybraneButtonActionPerformed

    private void ulozitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulozitButtonActionPerformed
        database.updateVybraneMesta(vybraneMesta);
        dispose();
    }//GEN-LAST:event_ulozitButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PridatVybraneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PridatVybraneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PridatVybraneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PridatVybraneForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PridatVybraneForm dialog = new PridatVybraneForm(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton odobratVybraneButton;
    private javax.swing.JButton pridatVybraneButton;
    private javax.swing.JButton ulozitButton;
    private javax.swing.JList vsetkyMestaList;
    private javax.swing.JList vybraneMestaList;
    private javax.swing.JButton zavrietButton;
    // End of variables declaration//GEN-END:variables
}
